-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 20:06:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancolivraria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancolivraria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancolivraria` ;
USE `bancolivraria` ;

-- -----------------------------------------------------
-- Table `bancolivraria`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancolivraria`.`usuarios` (
  `idusuarios` INT NOT NULL auto_increment,
  `nome_user` VARCHAR(250) NULL,
  `email_user` VARCHAR(250) NOT NULL,
  `senha_user` VARCHAR(45) NOT NULL,
  `cpf_user` VARCHAR(15) NULL,
  `telefone_user` VARCHAR(17) NULL,
  PRIMARY KEY (`idusuarios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancolivraria`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancolivraria`.`enderecos` (
  `idenderecos` INT NOT NULL auto_increment,
  `logradouro` VARCHAR(100) NULL,
  `numero` VARCHAR(4) NULL,
  `cep` INT NULL,
  `cidade` VARCHAR(60) NULL,
  `estado` VARCHAR(45) NULL,
  `idusuarios` INT NOT NULL,
  PRIMARY KEY (`idenderecos`, `idusuarios`),
  INDEX `fk_enderecos_usuarios1_idx` (`idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_usuarios1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `bancolivraria`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancolivraria`.`formas_pagamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancolivraria`.`formas_pagamentos` (
  `idformas_pagamentos` INT NOT NULL auto_increment,
  `tipo_pagamento` VARCHAR(45) NULL,
  `desconto` DECIMAL(5,2) NULL,
  PRIMARY KEY (`idformas_pagamentos`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bancolivraria`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancolivraria`.`livros` (
  `idlivros` INT NOT NULL auto_increment,
  `imagem` LONGTEXT NULL,
  `titulo_livro` VARCHAR(250) NOT NULL,
  `anopublicacao` DATE NULL,
  `descricao` LONGTEXT NULL,
  `estoque` INT NOT NULL,
  `preco` DECIMAL(10,0) NOT NULL,
  `nome_autor` VARCHAR(250) NOT NULL,
  `nome_genero` VARCHAR(100) NOT NULL,
  `nome_editora` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`idlivros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancolivraria`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancolivraria`.`compras` (
  `idcompras` INT NOT NULL auto_increment,
  `datacompra` DATE NULL,
  `total` DECIMAL(10,0) NOT NULL,
  `idusuarios` INT NOT NULL,
  `idformas_pagamentos` INT NOT NULL,
  `idlivros` INT NOT NULL,
  PRIMARY KEY (`idcompras`, `idusuarios`, `idformas_pagamentos`, `idlivros`),
  INDEX `fk_compras_usuarios1_idx` (`idusuarios` ASC) VISIBLE,
  INDEX `fk_compras_formas_pagamentos1_idx` (`idformas_pagamentos` ASC) VISIBLE,
  INDEX `fk_compras_livros1_idx` (`idlivros` ASC) VISIBLE,
  CONSTRAINT `fk_compras_usuarios1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `bancolivraria`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_formas_pagamentos1`
    FOREIGN KEY (`idformas_pagamentos`)
    REFERENCES `bancolivraria`.`formas_pagamentos` (`idformas_pagamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_livros1`
    FOREIGN KEY (`idlivros`)
    REFERENCES `bancolivraria`.`livros` (`idlivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancolivraria`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancolivraria`.`favoritos` (
  `idfavoritos` INT NOT NULL auto_increment,
  `idlivros` INT NOT NULL,
  `idusuarios` INT NOT NULL,
  PRIMARY KEY (`idfavoritos`, `idlivros`, `idusuarios`),
  INDEX `fk_favoritos_livros_idx` (`idlivros` ASC) VISIBLE,
  INDEX `fk_favoritos_usuarios1_idx` (`idusuarios` ASC) VISIBLE,
  CONSTRAINT `fk_favoritos_livros`
    FOREIGN KEY (`idlivros`)
    REFERENCES `bancolivraria`.`livros` (`idlivros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_usuarios1`
    FOREIGN KEY (`idusuarios`)
    REFERENCES `bancolivraria`.`usuarios` (`idusuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bancolivraria`;

INSERT INTO `livros` (`idlivros`, `imagem`, `titulo_livro`, `anopublicacao`, `descricao`, `estoque`, `preco`, `nome_autor`, `nome_genero`, `nome_editora`) VALUES
(1, 'https://m.media-amazon.com/images/I/91M9xPIf10L._SL1500_.jpg', 'O Hobbit', '1937-09-21', 'A aventura de Bilbo Bolseiro em uma jornada épica para recuperar o tesouro guardado por Smaug, o dragão.', 10, 50, 'J.R.R. Tolkien', 'Fantasia', 'HarperCollins'),
(2, 'https://m.media-amazon.com/images/I/819js3EQwbL._SL1500_.jpg', '1984', '1949-06-08', 'Um clássico da distopia, onde o Grande Irmão está sempre observando.', 15, 45, 'George Orwell', 'Ficção Científica', 'Companhia das Letras'),
(3, 'https://m.media-amazon.com/images/I/81ibfYk4qmL._SL1500_.jpg', 'Harry Potter e a Pedra Filosofal', '1997-06-26', 'O primeiro livro da saga de Harry Potter, onde o jovem descobre ser um bruxo.', 20, 55, 'J.K. Rowling', 'Fantasia', 'Rocco'),
(4, 'https://m.media-amazon.com/images/I/51nNwwVSclL._SL1007_.jpg', 'O Pequeno Príncipe', '1943-04-06', 'Uma história atemporal sobre amizade e amor.', 30, 30, 'Antoine de Saint-Exupéry', 'Ficção', 'Agir'),
(5, 'https://m.media-amazon.com/images/I/91Q2QLxT6BL._SL1500_.jpg', 'Dom Quixote', '1605-01-16', 'As aventuras do cavaleiro errante Dom Quixote e seu fiel escudeiro, Sancho Pança.', 12, 65, 'Miguel de Cervantes', 'Clássico', 'Penguin');

select * from livros;


select * from usuarios;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
